## Experiment 2: Explore, visualize, transform and summarize input datasets for building Classification/regression/prediction models.

## Software Used: Google colaboratory---


# **PyCaret for Classification**
---
- It is a bundle of many Machine Learning algorithms.
- Only three lines of code is required to compare 20 ML models.
- Pycaret is available for:
    - Classification
    - Regression
    - Clustering

---

### **Self Learning Resource**
1. Tutorial on Pycaret <a href="https://pycaret.readthedocs.io/en/latest/tutorials.html"> Click Here</a> 

2. Documentation on Pycaret-Classification: <a href="https://pycaret.org/Classification/"> Click Here </a>

---

### **In this experiment we will learn:**

- Getting Data: How to import data from PyCaret repository
- Setting up Environment: How to setup an experiment in PyCaret and get started with building regression models
- Create Model: How to create a model, perform cross validation and evaluate regression metrics
- Tune Model: How to automatically tune the hyperparameters of a regression model
- Plot Model: How to analyze model performance using various plots
- Finalize Model: How to finalize the best model at the end of the experiment
- Predict Model: How to make prediction on new / unseen data
- Save / Load Model: How to save / load a model for future use

---

#### **(a) Install Pycaret**

Exclamation sign: It means run it as a shell command rather than a notebook command. This is actually not specific to pip, but really any shell command from the iPython notebook. In computing, a shell is a computer program which exposes an operating system's services to a human user or other program. 

&> /dev/null: /dev/null is the null file. Anything written to it is discarded.

Together they mean "throw away any error messages".

In [ ]:
!pip install pycaret &> /dev/null
print ("Pycaret installed sucessfully!!")

Pycaret installed sucessfully!!

#### **(b) Get the version of the pycaret**

In [ ]:
## Utils is a collection of small Python functions and classes which make common patterns shorter and easier.
from pycaret.utils import version
version()

'2.3.2'

---
# **1. Classification: Basics**
---

### **1.1 Loading Dataset - Loading dataset from pycaret**

In [ ]:
from pycaret.datasets import get_data

# No output

---
### **1.2 Get the list of datasets available in pycaret (55)**
---

In [ ]:
# Internet connection is required
dataSets = get_data('index')

                             Dataset    Data Types  ... # Attributes Missing Values
0                            anomaly  Multivariate  ...           10              N
1                             france  Multivariate  ...            8              N
2                            germany  Multivariate  ...            8              N
3                               bank  Multivariate  ...           17              N
4                              blood  Multivariate  ...            5              N
5                             cancer  Multivariate  ...           10              N
6                             credit  Multivariate  ...           24              N
7                           diabetes  Multivariate  ...            9              N
8                    electrical_grid  Multivariate  ...           14              N
9                           employee  Multivariate  ...           10              N
10                             heart  Multivariate  ...           16              N
11                     heart_disease  Multivariate  ...           14              N
12                         hepatitis  Multivariate  ...           32              Y
13                            income  Multivariate  ...           14              Y
14                             juice  Multivariate  ...           15              N
15                               nba  Multivariate  ...           21              N
16                              wine  Multivariate  ...           13              N
17                         telescope  Multivariate  ...           11              N
18                           titanic  Multivariate  ...           11              Y
19  us_presidential_election_results  Multivariate  ...            7              N
20                             glass  Multivariate  ...           10              N
21                              iris  Multivariate  ...            5              N
22                             poker  Multivariate  ...           11              N
23                         questions  Multivariate  ...            4              N
24                         satellite  Multivariate  ...           37              N
25                               CTG  Multivariate  ...           40              Y
26                          asia_gdp  Multivariate  ...           11              N
27                         elections  Multivariate  ...           54              Y
28                          facebook  Multivariate  ...           12              N
29                               ipl  Multivariate  ...           25              N
30                         jewellery  Multivariate  ...            4              N
31                              mice  Multivariate  ...           82              Y
32                         migration  Multivariate  ...           12              N
33                           perfume  Multivariate  ...           29              N
34                           pokemon  Multivariate  ...           13              Y
35                        population  Multivariate  ...           56              Y
36                     public_health  Multivariate  ...           21              N
37                             seeds  Multivariate  ...            7              N
38                         wholesale  Multivariate  ...            8              N
39                            tweets          Text  ...            2              N
40                            amazon          Text  ...            2              N
41                              kiva          Text  ...            7              N
42                               spx          Text  ...            4              N
43                         wikipedia          Text  ...            3              N
44                        automobile  Multivariate  ...           26              Y
45                              bike  Multivariate  ...           15              N
46                            boston  Multivariate  ...           14              N
47                          concrete  Multivariate  ...            9              N
48                           diamond  Multivariate  ...            8              N
49                            energy  Multivariate  ...           10              N
50                            forest  Multivariate  ...           13              N
51                              gold  Multivariate  ...          121              N
52                             house  Multivariate  ...           81              Y
53                         insurance  Multivariate  ...            7              N
54                        parkinsons  Multivariate  ...           22              N
55                           traffic  Multivariate  ...            8              N

[56 rows x 8 columns]

---
### **1.3 Get diabetes dataset**
---

In [ ]:
diabetesDataSet = get_data("diabetes")    # SN is 7
# This is binary classification dataset. The values in "Class variable" have two (binary) values.
print(type(diabetesDataSet))

   Number of times pregnant  ...  Class variable
0                         6  ...               1
1                         1  ...               0
2                         8  ...               1
3                         1  ...               0
4                         0  ...               1

[5 rows x 9 columns]

<class 'pandas.core.frame.DataFrame'>

Read data from file

In [ ]:
#import pandas as pd
#diabetesDataSet = pd.read_csv("diabetes.csv")

In [ ]:
diabetesDataSet.columns

Index(['Number of times pregnant',
       'Plasma glucose concentration a 2 hours in an oral glucose tolerance test',
       'Diastolic blood pressure (mm Hg)', 'Triceps skin fold thickness (mm)',
       '2-Hour serum insulin (mu U/ml)',
       'Body mass index (weight in kg/(height in m)^2)',
       'Diabetes pedigree function', 'Age (years)', 'Class variable'],
      dtype='object')

In [ ]:
#Get the statistical summary of the dataset
diabetesDataSet.describe()

       Number of times pregnant  ...  Class variable
count                768.000000  ...      768.000000
mean                   3.845052  ...        0.348958
std                    3.369578  ...        0.476951
min                    0.000000  ...        0.000000
25%                    1.000000  ...        0.000000
50%                    3.000000  ...        0.000000
75%                    6.000000  ...        1.000000
max                   17.000000  ...        1.000000

[8 rows x 9 columns]

In [ ]:
print("type(diabetesDataSet)-->",type(diabetesDataSet))

type(diabetesDataSet)--> <class 'pandas.core.frame.DataFrame'>

In [ ]:
##Get the dimention of the dataset

In [ ]:
print("diabetesDataSet.shape -->", diabetesDataSet.shape)
print("Rows     -->", diabetesDataSet.shape[0])  ##axis 0---row
print("Columns  -->", diabetesDataSet.shape[1])   ###column

In [ ]:
### Show top 5 rows of the dataset

In [ ]:
diabetesDataSet.head()

In [ ]:
## Accessing data from dataset - Part 1 (using loc - Column Names)

In [ ]:
# Syntax --> loc[ ROW, COL_Names_in_List ]

#diabetesDataSet.loc[:, ['Diabetes pedigree function','Age (years)']]

# Also Try
#diabetesDataSet.loc[:10 , ['Diabetes pedigree function','Age (years)']]
diabetesDataSet.loc[10:100 , ['Diabetes pedigree function','Age (years)']]

In [ ]:
## Accessing data from dataset - Part 2 (using iloc - Column position)

In [ ]:
# Syntax --> iloc[ ROW, COL_Position]

#diabetesDataSet.iloc[0:10, 5:]

# Also Try
#diabetesDataSet.iloc[10:100, :-2]
diabetesDataSet.iloc[20:30, 1:5]

    Plasma glucose concentration a 2 hours in an oral glucose tolerance test  ...  2-Hour serum insulin (mu U/ml)
20                                                126                         ...                             235
21                                                 99                         ...                               0
22                                                196                         ...                               0
23                                                119                         ...                               0
24                                                143                         ...                             146
25                                                125                         ...                             115
26                                                147                         ...                               0
27                                                 97                         ...                             140
28                                                145                         ...                             110
29                                                117                         ...                               0

[10 rows x 4 columns]

In [ ]:
## Get the mean of the all the columns present in the dataset

In [ ]:
diabetesDataSet.mean()
# What is the output?
#df.head(50).mean()
#df.tail(50).mean()

Number of times pregnant                                                      3.845052
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    120.894531
Diastolic blood pressure (mm Hg)                                             69.105469
Triceps skin fold thickness (mm)                                             20.536458
2-Hour serum insulin (mu U/ml)                                               79.799479
Body mass index (weight in kg/(height in m)^2)                               31.992578
Diabetes pedigree function                                                    0.471876
Age (years)                                                                  33.240885
Class variable                                                                0.348958
dtype: float64

In [ ]:
## Get the maximum of each column in the dataset
diabetesDataSet.max()

Number of times pregnant                                                     17.00
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    199.00
Diastolic blood pressure (mm Hg)                                            122.00
Triceps skin fold thickness (mm)                                             99.00
2-Hour serum insulin (mu U/ml)                                              846.00
Body mass index (weight in kg/(height in m)^2)                               67.10
Diabetes pedigree function                                                    2.42
Age (years)                                                                  81.00
Class variable                                                                1.00
dtype: float64

In [ ]:
## Drop NA values (delete rows)

In [ ]:
diabetesDataSet.isnull().sum()
#diabetesDataSet.dropna()

Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    0
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index (weight in kg/(height in m)^2)                              0
Diabetes pedigree function                                                  0
Age (years)                                                                 0
Class variable                                                              0
dtype: int64

In [ ]:
## Drop the columns where there are null values

In [ ]:
diabetesDataSet.dropna(axis = 'columns')

In [ ]:
## Fill the null values with '0'

In [ ]:
diabetesDataSet.fillna(0)

In [ ]:
## Bar graph

In [ ]:
## Scatter plot

In [ ]:
## Subplot

In [ ]:
### TASK: Load the dataset from pycaret for regression/classification problem, explore and summarize it with adequate visualizations.